### ISSUE TITLE
"TypeError: [slidername].noUiSlider.on is not a function", pips not working.

### ISSUE THREAD

**Issue by JustinWestphal** [rcy/meteor-nouislider#7]
Using the UISlider package for Meteor released on atmosphere.

.on apparently isn't a function that works with Meteor. What is the solution here? Additionally, pips don't work. Implementing them exactly as shown in the docs and they aren't rendering in Meteor.

**Comment by dkoo761** [comment]
Hey @JustinWestphal, I ran into the exact same 2 problems just now :)

One thing to keep in mind is that this package is tracking version 7 of noUiSlider but the docs on that package's website are for version 8. So unfortunately, the 2 problems you mentioned above appear to be somewhat due to changes between version 7 and 8.

After some digging around in the source code I figured out some solutions:

The `update` event didn't work for me but the `change` event did. You can look at the source code to see if there are any other events you might need. I spotted 'change', 'slide' and 'set' upon a quick glance. In Meteor, the events are handled in the template event handler:

```javascript
Template.myTemplate.events({
  'change #my-slider': function (event) {
    console.log('slider changed!!!');
  }
});
```
As for pips, the way to use it has also changed. You need to initialize it in the old version 7 way:

```javascript
  var sliderElem = $('#my-slider');
  sliderElem.noUiSlider({
      ....slider options.....
  });
  sliderElem.noUiSlider_pips({
      ....pips options: mode, etc.
  });
```

Let me know if you have any trouble getting the above working and I'll help you out.
